#! /bin/sh
### BEGIN INIT INFO
# Provides:          corvus
# Required-Start:    
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: Corvus Init script
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions
do_stop () {
    kill -9 `/var/run/corvus.pid`
}
do_start () {
    log_action_msg "Starting Corvus "
    ../src/corvus -n 10.254.127.37:6379,10.254.127.48:6379,10.254.127.49:6379 -t 4 -b 6379 -L debug ./corvus.conf  1>/var/log/corvus.log 2>/var/log/corvus.err &
    CORVUSPID=$!
    echo Startted Corvus with PID=$CORVUSPID
    echo $CORVUSPID > /var/run/corvus.pid
}
do_restart () {
do_stop
do_start
}
case "$1" in
  start)
    do_start
    ;;
  restart|reload|force-reload)
    do_restart
    exit 3
    ;;
  stop)
    do_stop
    ;;
  status)
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 3
    ;;
esac